services:
  flask-app:
    image: benl89/todo_app:1.3
    ports:
    - 5000:5000
    environment:
     - DB_HOST=mysql
    depends_on:
     mysql:
      condition: service_healthy
    volumes:
      - app-data:/app/static/images
  mysql:
    image: mysql:8.0.25
    environment:
     - MYSQL_ROOT_PASSWORD=admin
    healthcheck:
      test : ["CMD", "mysqladmin" , "ping" , "-h" , "localhost"]
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
   image: phpmyadmin/phpmyadmin
   ports:
    - 5012:80
   environment:
     - PMA_HOST=mysql
   depends_on:
     mysql:
      condition: service_healthy
volumes:
  mysql-data:
  app-data:
   




